version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "telemetria"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eg1x3dthwzad"
s3_prefix = "telemetria"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
